import Splash from './splash/Splash'
import Head from 'next/head'

const Main = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Splash />
    </div>

  )
}

export default Main